language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw
  
before_deploy:
  - export JAR_FILE=$(ls */target/*.jar)
  - git config --local user.name peterlacza
  - git config --local user.email lcz.peti@gmail.com
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: bfee34f23042472cf87d493a7c15282521bdd869
  file: "*/target/*.jar"
  skip_cleanup: true
  file_glob: true
  on:
    repo: recipeRepo
    tags: true
    all_branches: true
