language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw
  
before_deploy:
      - git config --local user.name peterlacza
      - git config --local user.email lcz.peti@gmail.com
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG

deploy:
  provider: heroku
  api_key: 
    secure: 6a02b45c-de3f-4f6b-9fa4-fb9685294712
  skip_cleanup: true
