language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw
  
before_deploy:
  - export JAR_FILE=$(ls */target/*.jar)
  
deploy:
  provider: releases
  api_key: bfee34f23042472cf87d493a7c15282521bdd869
  file: "*/target/*.jar"
  skip_cleanup: true
  file_glob: true
  on:
    repo: recipeRepo/artifacts
    tags: true
    all_branches: true
