language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw
  
before_deploy:
  - export TRAVIS_TAG=True
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
  - git config --local user.name peterlacza
  - git config --local user.email lcz.peti@gmail.com
  - export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
  - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"


deploy:
  provider: releases
  api_key: 
    secure: bfee34f23042472cf87d493a7c15282521bdd869
  file: "target/*.jar"
  skip_cleanup: true
  file_glob: true
  overwrite: true
  on:
    tags: true
    all_branches: true