language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw
  
deploy:
  provider: releases
  api_key: bfee34f23042472cf87d493a7c15282521bdd869
  file: artifacts/
  skip_cleanup: true
  on:
    tags: true
